### PR TITLE
Updates Surge, allows for minor releases to Surge package

### PR DESCRIPTION
**Pull request by kennethormandy**
This should allow for 0.x updates to the Surge package, without needing a new release of this package. I also updated the lockfile.

I suppose it could also be removed and added as a `peerDependency` instead.

### CODE REVIEW

**Comment by mattc41190** [comment]
I bumped a little past this:

https://github.com/surge-sh/gulp-surge/pull/9/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R14

**Comment by sintaxi** [comment]
Thanks @mattc41190

**Comment by sintaxi** [comment]
@mattc41190 I just published `gulp-surge@0.1.4` for you.

**Comment by mattc41190** [comment]
@sintaxi  No worries! Thanks for checking in so fast. Let me know how #9 looks when you have a moment and thank you very much for surge. It's lovely 😌

**Pull request merged**
