### PR TITLE
updates surge to resolve vulnerable hoek dependency

### PR DESCRIPTION
**Pull request by SiAshbery**

### CODE REVIEW

**Comment by benabraham** [comment]
@sintaxi Can you please merge this? Thanks.

**Comment by sintaxi** [comment]
Ok its merged. Needs to be published by @kennethormandy though.

**Comment by kennethormandy** [comment]
@sintaxi You have permission to publish now! https://www.npmjs.com/package/gulp-surge

**Comment by sintaxi** [comment]
Thanks @kennethormandy!

**Comment by sintaxi** [comment]
Ok @benabraham. Just published `v0.1.3`.

**Comment by benabraham** [comment]
Thanks! 
Unfortunately there are still some vulnerabilites present 😢. Would like to fix this, but don't know how.

**Pull request merged**
